### ISSUE TITLE
Get guide not work

### ISSUE THREAD

**Issue by hannibal1986** [Dionakra/arenavision-scraper#1]
with comand:
const { getFullGuide } = require('arenavision-scraper');
getFullGuide().then(res => {
  console.log(JSON.stringify(res))
})

result with no channels:
[{"day":"18/07/2019","time":"21:00 CEST","sport":"SOCCER","competition":"UEFA EUROPA LEAGUE","event":"LEGIA WARSZAWA - EUROPA","channels":[]},{"day":"19/07/2019","time":"00:00 CEST","sport":"SOCCER","competition":"FRIENDLY MATCH","event":"SAINT ETIENNE - MONTPELLIER","channels":[]},{"day":"19/07/2019","time":"02:00 CEST","sport":"SOCCER","competition":"USA MLS","event":"CINCINNATI - DC UNITED","channels":[]}]

**Comment by Dionakra** [comment]
Hi, 

Which version is it? It should work on the latest version (1.0.25, just updated today).

**Comment by hannibal1986** [comment]
With the new version works fine👍
